### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Schoolsuzuran** [yagiz/ScreenshotSharer#1]
I open the file and start project as a white screen.
what happened?
thank you.

**Comment by yagiz** [comment]
The project in this repository is only for build testing. It's actually not a example project.

But still, if you run the project on a device and take a screenshot you can see the screenshot sharer view controller is presented.

In near future I'll change file structure of the repository and provide some examples.

**Comment by Schoolsuzuran** [comment]
Ok, I will waiting to you.
Thanks you  : )

**Comment by yagiz** [comment]
I updated the structure of repository and released a new clean version. You can now download the examples and run the projects on real device and test it. 

Actual source code is not changed, you don't need to update the pod.

**Comment by Schoolsuzuran** [comment]
Wowww! This is very nice project.  
Thanks you : )
