### ISSUE TITLE
sorry again

### ISSUE THREAD

**Issue by Schoolsuzuran** [yagiz/ScreenshotSharer#2]
sorry again , 
Why does device change every time a new app version is built/installed?
Do you have method  edit?
sorry, i am new developer  for Swift
Thanks you

**Comment by Schoolsuzuran** [comment]
I try  solution this question  , But i don't can solution  this project. 
Please help me.
Thank very much

**Comment by yagiz** [comment]
I couldn't understand what you mean. Could you please be more specific about your issue?

**Comment by Schoolsuzuran** [comment]
Every time at run project this will  install application new every time.
Normal application  run  don't install application new every time. 
Why ? and I will edit code ?

**Comment by Schoolsuzuran** [comment]
For example, I can install 3 free programs for iPhone.
"Screenshots" is the third app. Time to run the Xcode alert The maximum number of apps for free development profiles has been reached..
There are  no normal  notifications at run all , even if the project is running again. (project another)

**Comment by yagiz** [comment]
Others also experience this issue you are talking about:
https://forums.developer.apple.com/thread/73333 

It seems like a Xcode bug. I don't think this is related to project itself.

**Comment by Schoolsuzuran** [comment]
Ok I understand. 
Thank you so much.
