### ISSUE TITLE
Unable to see how it works

### ISSUE THREAD

**Issue by raihassen** [yagiz/ScreenshotSharer#3]
Hi,
I am sorry, but I am trying to run examples to see this works. I am taking screenshots, as suggested, but unfortunately it is not showing share screen.

**Comment by yagiz** [comment]
Did you try to run examples on device right? And which examples did you try to run?

**Comment by raihassen** [comment]
I tried all three, but unfortunately it says run, and take screenshot. And taking screenshot did not change anything. Anyway thanks.

**Comment by yagiz** [comment]
I try to understand where the problem is. Would you share the iOS version/model of the device?
