### ISSUE TITLE
It works in ViewController itself, but not working if put code in parent/super ViewController.

### ISSUE THREAD

**Issue by aloveric** [yagiz/ScreenshotSharer#4]
If there are many views, it should put times  with same code in each view.
Could I put it in parent view once.

**Comment by yagiz** [comment]
So you have a base view controller:
BaseViewController

And you have another view controller that extends base:
AViewController: BaseViewController

When you take screenshot of AViewController you see that it doesn't work. Did I get it? @aloveric

**Comment by aloveric** [comment]
@yagiz Yes.
I try it again today and it works now (BTW, I did same code yesterday but not work).
Thanks.
