### ISSUE TITLE
StatusBar in final screenshot image?

### ISSUE THREAD

**Issue by aloveric** [yagiz/ScreenshotSharer#6]
Is it available in screenshot?

**Comment by yagiz** [comment]
Yes. If you want the status bar to be visible in the screenshot image, you can 
`sssharer.registerScreenCapturer`

It has `cropStatusBar` property. If it's true, status bar is also included in the final image. @aloveric

**Comment by aloveric** [comment]
` sssharer.registerScreenCapturer(cropStatusBar: false, cropRect: CGRect.zero, captureBlock: { (image, screenshotSharerViewController) in`

Sure, I use this code. It has StatusBar but it is just blank without any carrier and battery info.

**Comment by yagiz** [comment]
It seems that you can't take screenshot of the status bar without using private API. So this is not possible right now. @aloveric

**Comment by aloveric** [comment]
Got it, thanks.
I don't think we could pass this API in iTunes review, ha.
@yagiz
